name: commit ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Calculate JNI cache hash
#        id: cache-hash
#        run: script/cache-hash.sh

#      - name: Fetch JNI cache
#        uses: actions/cache@v2
#        id: jni-cache
#        with:
#          path: "app/prebuilt"
#          key: jni-debug-${{ steps.cache-hash.outputs.hash }}

      - name: Fetch submodules
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: |
          git submodule update --init --recursive
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

#      - name: Spotless code style check
#        run: make spotless

#      - name: Install dependency
#        if: ${{ !steps.jni-cache.outputs.cache-hit }}
#        run: ./script/dependency.sh


      - name: gradle prepare
        run: gradle wrapper
        
      - name: Build prepare
        run: chmod +x ./gradlew
        
#      - name: Build with Gradle
#        run: ./gradlew --warning-mode all build

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Build Trime
        #run: ./gradlew tasks
        run: make debug
        # run: make release

      - name: Add JNI cache
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: cp -R app/build/intermediates/stripped_native_libs/debug/out/lib app/prebuilt

      - name: Upload Trime artifact
        uses: actions/upload-artifact@v2
        with:
          name: trime.zip
          #path: app/build/outputs/apk/**/*.apk
          path: app/build/outputs/apk/**/*arm64*.apk
          # keep 90 days
          retention-days: 90
